-- AlterTable
ALTER TABLE `UploadsHistory` MODIFY `detectionStatus` ENUM('VIOLENCE_DETECTED', 'NON_VIOLENCE', 'INCONCLUSIVE', 'GUN_DETECTED', 'NO_GUN', 'FIRE_DETECTED', 'NO_FIRE') NULL;

-- AlterTable
ALTER TABLE `UserStats` MODIFY `lastDetectionStatus` ENUM('VIOLENCE_DETECTED', 'NON_VIOLENCE', 'INCONCLUSIVE', 'GUN_DETECTED', 'NO_GUN', 'FIRE_DETECTED', 'NO_FIRE') NULL;
